name: 'Continuous Integration'

on:
  tags:
    - '*.*.*'

jobs:
  push:
    name: 'Push image'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Log in to the Container registry'
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ secrets.REGISTRY_HOST }}'
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      - name: 'Build'
        uses: 'docker/build-push-action@v5'
        with:
          pull: false
          push: true
          tags: 'jeanberu/mailcatcher:${{ github.ref_name }}'
