name: 'Continuous Integration'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  push:
    name: 'Run tests'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Log in to the Container registry'
        uses: 'docker/login-action@v3'
        with:
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      - name: 'Build'
        uses: 'docker/build-push-action@v5'
        with:
          tags: 'jeanberu/mailcatcher:latest'
          platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8'
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'
      - name: 'Start mailcatcher'
        run: 'docker run --detach --publish 1025:1025 --publish 1080:1080 jeanberu/mailcatcher:latest'
      - name: 'Install Ruby dependencies'
        uses: 'ruby/setup-ruby@v1'
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: 'Wait for mailcatcher'
        run: |
          while ! nc -z 0.0.0.0 1025 </dev/null; do echo Waiting for SMTP to start...; sleep 1; done
          while ! nc -z 0.0.0.0 1080 </dev/null; do echo Waiting for API to start...; sleep 1; done
        timeout-minutes: 1
      - name: 'Run tests'
        run: 'bundle exec rspec spec/*'
