name: 'Publish image'

on:
  push:
    tags: ['*.*.*']

jobs:
  tests:
    name: 'Run tests'
    uses: './.github/workflows/ci.yml'
    secrets: 'inherit'
  push:
    name: 'Push image'
    needs: ['tests']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Log in to the Container registry'
        uses: 'docker/login-action@v3'
        with:
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      - name: 'Build'
        uses: 'docker/build-push-action@v5'
        with:
          pull: false
          push: true
          tags: 'jeanberu/mailcatcher:${{ github.ref_name }},jeanberu/mailcatcher:latest'
          platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8'
